# Generated by Django 4.1 on 2022-09-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
